tags:
  - name: Produtos
    description: Gerenciamento de produtos.

paths:
  /produtos:
    get:
      summary: Obter todos os produtos
      tags: [Produtos]
      description: Retorna uma lista de todos os produtos. Este endpoint é público.
      responses:
        '200':
          description: Uma lista de produtos.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Success
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Produto'
    post:
      summary: Criar um novo produto
      tags: [Produtos]
      security:
        - bearerAuth: []
      description: Adiciona um novo produto. Requer autenticação e upload de imagem.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - nome
              properties:
                imagem:
                  type: string
                  format: binary
                  description: "Arquivo de imagem do produto (limite 10MB)."
                altText:
                  type: string
                  description: Texto alternativo para a imagem.
                  example: "imagem do produto"
                nome:
                  type: string
                  example: "Buquê de Rosas Secas"
                descricao:
                  type: string
                  example: "Um lindo buquê com rosas vermelhas desidratadas."
                preco:
                  type: number
                  format: float
                  description: Preço do produto.
                  example: 25.50
                recomendado:
                  type: boolean
                  default: false
                tipo:
                  type: string
                  example: "Buquê"
                disponiveis:
                  type: integer
                  description: Quantidade disponível em estoque.
                  example: 10
      responses:
        '201':
          description: Produto criado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Produto criado com sucesso.
                  data:
                    $ref: '#/components/schemas/Produto'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'

  /produtos/{id}:
    get:
      summary: Obter produto por ID
      tags: [Produtos]
      description: Retorna um produto específico pelo seu ID. Este endpoint é público.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dados do produto.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Success
                  data:
                    $ref: '#/components/schemas/Produto'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      summary: Atualizar um produto por ID
      tags: [Produtos]
      security:
        - bearerAuth: []
      description: Atualiza um produto existente. Requer autenticação. Pode incluir um novo upload de imagem.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                imagem:
                  type: string
                  format: binary
                  description: "Arquivo de imagem do produto (limite 10MB)."
                altText:
                  type: string
                  description: Texto alternativo para a imagem.
                  example: "imagem do produto"
                nome:
                  type: string
                  example: "Buquê de Rosas Secas"
                descricao:
                  type: string
                  example: "Um lindo buquê com rosas vermelhas desidratadas."
                preco:
                  type: number
                  format: float
                  description: Preço do produto.
                  example: 25.50
                recomendado:
                  type: boolean
                tipo:
                  type: string
                  example: "Buquê"
                disponiveis:
                  type: integer
                  description: Quantidade disponível em estoque.
                  example: 10
      responses:
        '200':
          description: Produto atualizado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Produto atualizado com sucesso.
                  data:
                    $ref: '#/components/schemas/Produto'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '413':
          $ref: '#/components/responses/PayloadTooLarge'
    delete:
      summary: Deletar um produto por ID
      tags: [Produtos]
      security:
        - bearerAuth: []
      description: Deleta um produto. Requer autenticação.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Produto deletado com sucesso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Produto deletado com sucesso.
                  data:
                    type: object
                    nullable: true
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'