name: Node.js CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Wait for MongoDB to be ready
      run: |
        echo "Waiting for MongoDB to start..."
        until nc -z -w10 mongodb 27017; do
          echo "MongoDB is not yet available, waiting..."
          sleep 1
        done
        echo "MongoDB is up and running!"
      
    - name: Run tests
      run: npm test
      env:
        MONGO_URI: mongodb://mongodb:27017/jest_test_db
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        PORT: 8080